### ISSUE TITLE
Feature Request: Ability to specify a value to treasure and sell all treasure

### ISSUE THREAD

**Issue by Zamrod** [teroparvinen/foundry-party-inventory#1]
I was thinking for items that are "treasure" like a 50 gp gem or art or whatever it would be nice to just specify a value to for them and have a button to "Sell all treasure" which would put their full value (since treasure sells for full price in 5e) into the party inventory in order to easily split it.

**Comment by teroparvinen** [comment]
I have to draw a certain line to avoid uncontrolled feature creep. The argument against this is that the scratchpad is intended to foster role playing outside official item lists, and providing functionality like this would encourage parameterising items to rules based criteria. All feedback is appreciated though and if the direction of the module changes any time in the future, they will be taken into consideration.
