### ISSUE TITLE
Conflict with Inventory+

### ISSUE THREAD

**Issue by TheDSeraph** [teroparvinen/foundry-party-inventory#11]
Having Inventory+ enabled causes error when trying to drag items to character sheets. Nothing happens and console shows this error
![image](https://user-images.githubusercontent.com/108111780/175461256-8bf62df4-aeb8-43db-a97a-1a763d38115b.png)

**Comment by p4535992** [comment]
@TheDSeraph should be solved on inventory plus side with version 0.5.11
