### ISSUE TITLE
[Feature Request] Split some not all Currency

### ISSUE THREAD

**Issue by mouse0270** [teroparvinen/foundry-party-inventory#3]
Some times my players want to reward themselves with some of the rewards they have stored up.

It would be nice when splitting the gold that if at the top, it would show how much they have of each currency, but allow me them to change it and it would only split the new amount.

For example, if they were hoarding 500 gold but just wanted to split 100 of it among themselves, they could change the 500 to 100 and it would split that amount instead of the entire amount. Yes they could do this manually but it was a request they asked me to make either way.

**Comment by teroparvinen** [comment]
The intent of the module is to avoid any loot laying around unaccounted for either in ownership or encumbrance, that is why players can flag stuff from their own inventory to be displayed in the party inventory window. I have told my players that anything on the scratchpad is there temporarily, and if a call has to be made stuff left there might be ruled to be left behind or at least left on the ground somewhere closeby. I have to avoid feature creep in a module like this, and this is why I will leave this out.

The proper solution to this would perhaps be a "Party funds" module that would show how much currency everyone in the party is carrying, but that is too much clutter to include in this module, in my opinion.

All feedback is appreciated and if the direction of the module changes any time in the future, they will be taken into consideration.
