### ISSUE TITLE
SWADE system support?

### ISSUE THREAD

**Issue by SalieriC** [teroparvinen/foundry-party-inventory#4]
This module seems really useful for any game system. Would you be interested in creating a version suitable for the SWADE system? I'd be very happy to provide advice.

**Comment by teroparvinen** [comment]
Having now released multiple modules, I've decided to take a policy that if someone forks one of my modules and makes a functioning implementation that adds support for a game system, I will consider merging these as pull requests. A condition for this is that the implementation in general be such that it can be trusted to stay functional without me having to do testing with every release.

Unfortunately, that's all I can do with the time available for module development.

**Comment by SalieriC** [comment]
Understandable. Got my fingers in too many projects already but I might take a look at it post v10.
