### ISSUE TITLE
[Feature Request] Compatibility with Item Collection

### ISSUE THREAD

**Issue by SwordofSpirit** [teroparvinen/foundry-party-inventory#6]
You've made such an incredibly useful module here, that I'm now in a bind as to which module to use, because Party Inventory won't track items in containers in the Item Collection module. If that functionality could be implemented I could use both of these modules together without issue.

Thanks for your time!

**Comment by teroparvinen** [comment]
My policy with these is that if someone makes a working fork of my module with this functionality, I will consider merging it as a pull request. Unfortunately, I don't have the time to install and figure out how modules I'm not using myself work.
