### ISSUE TITLE
[Bug] Unable to reactivate inactive actors if all actors are set to inactive

### ISSUE THREAD

**Issue by Typhos** [teroparvinen/foundry-party-inventory#7]
When a user removes all character actors from the list to split currency to, the "includes X inactive actor(s)" link disappears. In order to get the actors back into the split window, the GM must make a new character actor and then reactive all party members. 

Ideally, either the "include X inactive actor(s)" link always remains visible, and/or you are not allowed to deselect the final party member from the split window.

**Comment by teroparvinen** [comment]
Thanks for the report, will be fixed in the next release
