### ISSUE TITLE
Quantity amount of items dragged from Party Inventory to Character Sheet error

### ISSUE THREAD

**Issue by bhi-elliot** [teroparvinen/foundry-party-inventory#9]
Thanks for the module! It's great!

If you drag something with a quantity, say Arrows (10), from the Party Inventory (PI) to a Character Sheet (CS) that already has a quantity, say Arrows (10), the new amount is added incorrectly. In the above example, the new amount becomes Arrows (1010).

To replicate this, click and drag Arrows (20) from a CS to the PI. Then split the stack, into 2 piles of (10). For fun, split one of those stacks again, so you have a stack of (10), a stack of (5), and a stack of (5). Drag the (10) pile to the CS. That works as expected. If you drag one of the (5) stacks to the CS, the amount on the CS becomes (105). Also note that the (5) stack in the PI does not delete. Dragging another (5) from PI to CS makes the total amount (1055).

Hope that makes sense.
Again, great module. Much appreciated!

**Comment by teroparvinen** [comment]
Thank you for the great bug report. Should be fixed in the next update.
